# Generated by Django 3.1.2 on 2020-10-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('floors', models.IntegerField()),
                ('built_on', models.DateField()),
                ('area', models.CharField(max_length=50)),
                ('bedrooms', models.IntegerField()),
                ('Bathrooms', models.IntegerField()),
                ('price', models.FloatField()),
                ('img', models.ImageField(upload_to='house-images/%Y/%m/%d/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
