# Generated by Django 3.1.2 on 2020-10-05 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='Bathrooms',
            new_name='bathrooms',
        ),
        migrations.AddField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='city',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={}, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
