# Generated by Django 3.1.2 on 2020-10-07 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201005_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house-images/%Y/%m/%d/')),
                ('multiImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_images', to='api.house')),
            ],
        ),
    ]
