# Generated by Django 3.1.2 on 2020-10-17 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_image'),
        ('users', '0002_customuser_favourites'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedHouses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourites', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.house')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
