# Generated by Django 3.1.2 on 2020-10-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_savedhouses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='favourites',
        ),
    ]
