# Generated by Django 3.1.2 on 2020-10-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201017_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedhouses',
            old_name='favourites',
            new_name='house',
        ),
    ]
